### PR TITLE
Add support for generating different 'Instruction' class

### PR DESCRIPTION
**Pull request by shlomoartsi**
A support is added to generate a different Instruction class (ie _MyInstruction_). For that we define an _IInstruction_  interface for _Instruction_ class. in addition a _IInstructionFactory_ is injected to the ctor of _Disassembler_ in order to generate a different class implementing _IInstruction_ . 
The backward compatibility is maintained, and if no implementation of _IInstructionFactory_ is injected than an  _InstructionFactory_ class  that generate the _Instruction_ class is used.

### CODE REVIEW

**Comment by justinstenning** [comment]
The PR doesn't appear to have your changes in it.

**Comment by shlomoartsi** [comment]
Hi,
I'll try to explain my required change in more details and examples.
I've used your project for implementing a binary obfuscation project. For that i needed to add more info for _Instruction_ class, such as previous and next instruction fields. I didn't want to add these fields on the project itself, but on my custom class that defines an instruction.
 I've found that the most structured way for doing this is to change the project to use interface of _IInstruction_ instead of actual class of _Instruction_ , and to use dependency injection for factory of _IInstruction_ implementation instead of using "_new Instruction()_" where needed.
An example for the dependency injection is the _Disassembler_ ctor. This injection allows the consumer of the project to have an actual control of the creation of _Instruction_ class (and by the way promote the testablity of Disassembler class):

_public Disassembler(IAssemblyCode code, ArchitectureMode architecture, ulong address = 0x0,
    bool copyBinaryToInstruction = false,
    Vendor vendor = Vendor.Any, **IInstructionFactory instructionFactory = null**)
{
            ...
            **if (instructionFactory == null)
            {
                this.InstructionFactory = new InstructionFactory();
            }
            else
            {
                this.InstructionFactory = instructionFactory;
            }**
            ...
}_

 using the factory:
        _public **IInstruction** NextInstruction()
        {
            int length = 0;
            if ((length = Udis86.udis86.ud_disassemble(ref _u)) > 0)
            {
                **var instruction = InstructionFactory.Create(ref _u, CopyBinaryToInstruction);**
                if (!instruction.Error)
                {
                    BytesDecoded += length;
                }
                return instruction;
            }
            return null;
        }_

**Comment by justinstenning** [comment]
@shlomoartsi are you saying you have made these changes and would like to prepare in a pull request, or is this a feature request? If a feature request, can you please update the issue #17 with these details also.

**Comment by shlomoartsi** [comment]
Hi,
Yes i've made those changes (and more) already and would like create a pull
request.
Regards,
Shlomo

**Pull request closed without merging**
