### PR TITLE
Added missing feature to offset into IAssemblyCode 

### PR DESCRIPTION
**Pull request by tgiphil**
- Removed some unused code
- Set some member fields to internal
- Added unit test for offset

### CODE REVIEW

**Comment by tgiphil** [comment]
Any chance to incorporate my patches?

**Comment by justinstenning** [comment]
Completely missed this one, sorry

**Comment by justinstenning** [comment]
@tgiphil please submit a pull against the Develop branch and I will merge it in. I'm not 100% sure I'm happy with making the original udis properties internal only as there may be uses for having them available - I'll have a think, but submit the pull request as is for now.

**Comment by tgiphil** [comment]
Done. 

I can revert out the changes related to making the udis properties. However, it just made sense to me to keep the low level, internal structures & classes as internal. And, if necessary, to build out a proper interfaces when that information needs to exposed.

**Comment by justinstenning** [comment]
Pull request #5 instead

**Pull request closed without merging**
